services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    env_file: deploy/.env.prod
    networks:
      - thechats-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mini-sentry-api.rule=Host(`logs.thechats.me`) && PathPrefix(`/api`)"
      - "traefik.http.routers.mini-sentry-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mini-sentry-api.priority=10"
      - "traefik.http.services.mini-sentry-api.loadbalancer.server.port=3001"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    restart: unless-stopped
    env_file: deploy/.env.prod
    environment:
      - PORT=3000
    networks:
      - thechats-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mini-sentry-dashboard.rule=Host(`logs.thechats.me`)"
      - "traefik.http.routers.mini-sentry-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mini-sentry-dashboard.priority=1"
      - "traefik.http.services.mini-sentry-dashboard.loadbalancer.server.port=3000"

networks:
  thechats-network:
    external: true
    name: thechats_thechats-network
